import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        <SidebarProvider>
          <div className="flex min-h-screen w-full ">
            <AppSidebar />

            <main className="flex-1 min-w-0">
              <SidebarInset className="">
                <div className="bg-white border-b border-[#e2e3e6] px-4 md:px-8 py-4 md:py-6 flex items-center gap-4">
                  <SidebarTrigger className="md:hidden" />
                  <h1 className="text-xl md:text-2xl font-semibold text-[#171c21]">
                    Profile
                  </h1>
                </div>
                {children}
              </SidebarInset>
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
