import type { Metadata } from "next";
import { inter, spectral, jetBrainsMono } from "@/app/fonts";
import "../globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { getUserPinnedBravoImage } from "@/lib/queries";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userSession = await auth();

  if (!userSession) {
    redirect("/login");
  }

  const pinnedBravo = await getUserPinnedBravoImage(userSession.user.id);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${spectral.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <SessionProvider>
          <SidebarProvider>
            <div className="flex min-h-screen w-full ">
              <AppSidebar
                user={userSession?.user || null}
                pinnedBravo={pinnedBravo}
              />

              <main className="flex-1 min-w-0">
                <SidebarInset className="">
                  <div className="bg-white border-b border-[#e2e3e6] px-4 md:px-8 py-4 md:py-6 flex items-center gap-4">
                    <SidebarTrigger className="md:hidden" />
                    <h1 className="text-xl md:text-2xl font-semibold text-[#171c21]">
                      Profile
                    </h1>
                  </div>
                  {children}
                </SidebarInset>
              </main>
            </div>
          </SidebarProvider>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
