import type { Metadata } from "next";
import { inter, spectral, jetBrainsMono } from "@/app/fonts";
import "../globals.css";
import { Footer } from "@/components/footer";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userSession = await auth();

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${spectral.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <SessionProvider>
          <Header userSession={userSession} />
          {children}
          <Footer />
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
