export const TAG_COLORS = {
  Illustration: "bg-[#CDFF98]",
  "Video Creation": "bg-[#AA9BFF]",
  "AI Art": "bg-[#8BB0FF]",
  Copywriting: "bg-[#FFC471]",
  Music: "bg-[#FF8787]",
  Animation: "bg-[#AA9BFF]",
  "3D Modeling": "bg-[#8BB0FF]",
  "Web Development": "bg-[#FFC471]",
  "Mobile Development": "bg-[#FF8787]",
  "Game Development": "bg-[#AA9BFF]",
  "UI/UX Design": "bg-[#8BB0FF]",
  "Graphic Design": "bg-[#FFC471]",
  "Product Design": "bg-[#FF8787]",
  "Illustration & Graphic Design": "bg-[#FF8787]",
  React: "bg-[#FFC471]",
  Photography: "bg-[#FF8787]",
  Web3: "bg-[#AA9BFF]",
  Computer: "bg-[#FF8787]",
};
